//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int ProductID { get; set; }
        public string NamePro { get; set; }
        public string Category { get; set; }
        public int Rate { get; set; }
        public double Price { get; set; }
        public int ImagePro { get; set; }
        public string IDVoucher { get; set; }
        public int Memory { get; set; }
        public int Color { get; set; }
        public string DesribeProduct { get; set; }
        public string Video { get; set; }
        public string ConnectNetwork { get; set; }
        public string SizeAndWeight { get; set; }
        public int Screen { get; set; }
        public int RearCam { get; set; }
        public int FrontCam { get; set; }
        public int Battery { get; set; }
    
        public virtual Battery Battery1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual FrontCamera FrontCamera { get; set; }
        public virtual ImagePro ImagePro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual Rate Rate1 { get; set; }
        public virtual RearCamera RearCamera { get; set; }
        public virtual Screen Screen1 { get; set; }
    }
}
